### ISSUE TITLE
Astcheck: stalls for objects with poorly determined orbits

### ISSUE THREAD

**Issue by dpieterse** [Bill-Gray/lunar#16]
When I tried matching some of my detections to all known objects (in MPCORB and in JPL's comet database, which I combined into a SOF-format catalogue using _mpc2sof.cpp_) using _astcheck.cpp_, I encountered some stalls. These happen when _astcheck_ attempts to match some of the comets with poorly determined orbits to my observation. Specifically this happens in the function _compute_asteroid_loc_ (called in line 708 in _astcheck_).

Example:
>      0011819  C2020 10 04.88134 01 00 32.05 -72 00 16.0          19.5 G      L66
When matching the observation above, I'm getting a stall when _astcheck_ attempts to match the observation to C/2002 Q6.

Could you add a time-out option to the position computation, so that whenever it stalls on an object like this, _astcheck_ simply skips it and continues with the next known object?

**Comment by Bill-Gray** [comment]
Thank you.  I tried your example case and got the same problem.

I suppose I could have done some sort of 'skip it' step,  but this is really a bug;  it should be fixed,  not simply side-stepped.  So I investigated a bit.  Turns out that when fed a single observation, astcheck was computing the object position for JD 0.  I've fixed this (commit 474b22a8b90f6f22d9b).  When I run it on your example,  it now figures out that it's C/2002 Q6.

I've used astcheck almost solely in "motion" mode (two or more observations,  so that identifications can be done on the basis of both position and motion).  The bug doesn't occur in that case,  so I never noticed it.  Apparently,  the occasional instances where I did have single observations/no motion never triggered the bug.

However,  I'm currently working on improving the program's abilities for handling single observations;  I have some folks who want to use it for "what objects are in this field" problems.  So there will be further fixes/improvements coming for this program that may (or may not) be useful for you.  It also means that if you run into other bugs or have suggestions for improvements,  this is an excellent time to mention them.

**Comment by dpieterse** [comment]
Thank you so much for you quick response and fix! 

I very much look forward to the further improvements you mention. I'm planning to run astcheck on all (single) detections made with the MeerLICHT & BlackGEM telescopes, to find asteroids in our data that we cannot identify with linking software (which requires at least 3 detections). And indeed, using it to predict which objects are in a field is also extremely useful.

The two suggestions that I currently have for improvements are:
- It would be great if _integrat_ can be used on the JPL comet database, so that the predictions of comet positions can be determined more accurately.
- A way to take orbital uncertainties into account, although this is difficult as there is no easy & quick way to get positional uncertainties for all objects from the MPC or JPL as far as I'm aware.

**Comment by dpieterse** [comment]
Perhaps I'm misunderstanding what the DASTCOM database is. I downloaded the JPL orbital elements of the comets from: https://ssd.jpl.nasa.gov/dat/ELEMENTS.COMET (as listed here https://ssd.jpl.nasa.gov/sb/elem_tables.html). When I try running integrat on this file, it doesn't recognize any of the comets for integration. 

Your documentation (https://www.projectpluto.com/pluto/integrat.htm#jpl_eph) doesn't mention running integrat on JPL's comets. It does mention running integrat on the MPC comet elements, which indeed works. But as you mention, using JPL comet elements would be preferable.
